import React, { useState } from "react";

// Tries a same-name .webp sibling first (generated by scripts/optimize_png.py
// for everything under public/pousadas and public/species at the time it
// last ran), and silently falls back to the original src via onError if that
// .webp 404s — which covers admin-uploaded photos added after the script ran
// and never got a sibling. <picture><source> can't do this: once the browser
// picks a source it doesn't retry on a failed fetch, so a missing .webp would
// render as a broken image instead of falling back.
type Props = React.ImgHTMLAttributes<HTMLImageElement> & { src: string };

export default function PictureImg({ src, ...imgProps }: Props) {
  const isLocalRaster = /^\/(pousadas|species)\/.+\.(png|jpe?g)$/i.test(src);
  const webpSrc = isLocalRaster ? src.replace(/\.(png|jpe?g)$/i, ".webp") : null;
  const [failed, setFailed] = useState(false);

  return (
    <img
      src={webpSrc && !failed ? webpSrc : src}
      loading="lazy"
      decoding="async"
      onError={webpSrc && !failed ? () => setFailed(true) : undefined}
      {...imgProps}
    />
  );
}
